### ISSUE TITLE
Operationalize master task

### ISSUE THREAD

**Issue by mimoo** [diem/whackadep#27]
To operationalize this we have to figure out a few things.

## Where do we want this to live?

* Association AWS 
* Novi AWS
* or both? After all we care two use cases: novi stuff (custody, SLEDGE) and diem stuff (AOS, diem-core)

## How do we want to deploy this?

* easy ECS
* easy EKS
* terraform of ECS
* terraform of EKS

([terraform pointer](https://github.com/novifinancial/libra-ops/blob/master/terraform/global-dev/github.tf#L507))

## do we also want to move mongodb to a managed service like documentDB? (

IMO hat's more work for no real benefit

## TODO

- [x] k8ify docker-compose with tool
- [ ] clean dockerfiles (see [this](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html))
- [ ] clean k8s files
- [ ] dev -> prod-ify frontend (vuejs)
- [ ] dev -> prod-ify backend (rocket)
- [ ] dev -> prod-ify mongodb (user, creds, persistent volume)
- [ ] helm/kustomize things
- [ ] load balancer to serve both frontend and backend on same domain (this might require us to move all the requests to the API behind a `/api` route)
- [ ] terraform apply that shit
- [ ] create github action flow to create releases and push them to ECR easily (Golang has this amazing [Goreleaser](https://github.com/goreleaser/goreleaser-action) tool that creates releases for you every time you create a tag in Github, does the same exist for Rust?) (maybe https://docs.github.com/en/actions/guides/publishing-docker-images)
- [ ] make sure errors are logged somewhere, and create alerts
- [ ] figure access control
