### ISSUE TITLE
New skeleton page for Whackadep: Dependency health metrics

### ISSUE THREAD

**Issue by nasifimtiazohi** [diem/whackadep#58]
- [x] Add the (new) analysis page to Whackadep (#57)
- [x] display the list of dependencies based on the current HEAD of the repo (#57)
- [x] Add cron job to update the page periodically (#61)
